# Generated by Django 5.0.1 on 2024-01-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='image',
            field=models.FileField(blank=True, upload_to='museum_images/'),
        ),
    ]
